version: "3"
services:
  db:
    restart: always
    image: postgres:15.2
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  bot:
    build:
      context: ./Dockerfile/
    image: bot
    container_name:
      test_bot
    command:
      python test_bot.py
    env_file:
      - .env
    restart:
      always
    depends_on:
      - db