version: "3"
services:
  db:
    restart: always
    image: postgres:15.2
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./pgdata:/var/lib/postgresql/data
      # - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      # - ./new_database.sql:/docker-entrypoint-initdb.d/new_database.sql
    # network_mode: 'host'
    #ports:
     # - ${PORT}:5432

  bot:
    build:
      context: ./Dockerfile/
    image: bot
    container_name:
      test_bot
    command:
      python test_bot.py
    env_file:
      - .env
    restart:
      always
    depends_on:
      - db
volumes:
  db-data:
